"""
    Subscribe to /ee_pose_commands , where it will find these points and orientations generated by the circular_motion_ee.py script.

    Subscribe to the topic /end_effector_real_pose of type geometry_msgs.Vector3 returns the real
    positions and chi angle of Frame 3 of the real robot (to be able to compare).

    Will create an instance of JointMoverfrom the move.pyscript and an instance of
    MarkerBasics from the rviz_marker.py script. It will use them to move the arm to the calculated poses and publish the marker of the desired new pose.

    It will also create an instance of the method calculate_ik of the script ik_planar_arm.py, to be able to calculate the thetas to reach the position of the ellipses.
"""


#! /usr/bin/env python

import rospy
from planar_3dof_control.msg import EndEffector
from rviz_marker import MarkerBasics
from ik_planar_arm import ComputeIk
from move import JointMover




class objPublisher(object):

    def __init__(self):

        self.sub = rospy.Subscriber('/ee_pose_commands',EndEffector, self.getKinematics)
        self.DH = {'r1': 1.0, 'r2': 1.0, 'r3': 1.0}
        self.ik = ComputeIk(self.DH)
        self.movep = JointMover()
        

    def getKinematics(self, msg):
        x = msg.ee_xy_theta.x 
        y = msg.ee_xy_theta.y
        phi = msg.ee_xy_theta.z
        elbow  = msg.elbow_policy.data
        # print(x,y, elbow)
        angles, valid = self.calculate_ik(x, y, phi, elbow)
        # print(angles, valid)
        self.movep.move_all_joints(angles[0],angles[1],angles[2])
        
        

    def calculate_ik(self, Pee_x, Pee_y, chi, elbow_config):
        
        return self.ik.compute_ik(Pee_x, Pee_y, chi, elbow_config)


if __name__ == '__main__':
    rospy.init_node('publish_move', anonymous=True)
    finalObj = objPublisher()
    while not rospy.is_shutdown():
        pass







"""
catkin_create_pkg my_publisher_example_pkg rospy std_msgs
mkdir scripts
touch simple_topic_publisher.py
chmod +x simple_topic_publisher.py
rosrun my_publisher_example_pkg simple_topic_publisher.py

"""